**[Slide No. 5]**

1. Write a Program to check the version numpy installed .

In [1]:
import numpy
numpy.version.version

'1.20.1'

**[Slide No . 8]**

2. Write a program to create numpy 1-D array from list.

In [2]:
import numpy as np

#create numpy array
a = np.array([5, 8, 12])
print(a)

[ 5  8 12]


**[Slide No. 9]**

3. Write a program to Create a 2-D array .

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(x)


[[1 2 3]
 [4 5 6]]


**[Slide No . 11]**

5. a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])



What is the output [5 9] ?

In [4]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])
print(a[5,9])

IndexError: index 5 is out of bounds for axis 0 with size 3

**[Slide No.15]**

6. Correct the program .

import numpy as np

array=np.array([1,2,3,4,5,6])

print(array[-1:-5])

In [8]:
array=np.array([1,2,3,4,5,6])

print(array[0:1])

[1]


7. a=np.array([(1,5,9),(10,12,2),(5,7,8)])


Print the max value from first row ?

print min value from the first row ?

print the sum of all the element of second row ?




In [13]:
a=np.array([(1,5,9),(10,12,2),(5,7,8)])
maxValue = numpy.amax(a[0])
minValue = numpy.amin(a[0])
print("Maximum of First row",maxValue)
print("Minimum of First row",minValue)

Maximum of First row 9
Minimum of First row 1


**[Slide No. 16]**


8. Create a numpy array using a below numbers and print (1,3,5).

[1,2,3,4,5,6]



In [14]:
oddArr = np.array([1,2,3,4,5,6,7,8])

print("**The List of Odd Numbers in this oddArr Array***")
for i in oddArr:
    if (i % 2 != 0):
        print(i, end = "  ")

**The List of Odd Numbers in this oddArr Array***
1  3  5  7  

**[Slide No. 18]**

9. Create a  [3,4] numpy array and reshape it [4,3] numpy array.

In [20]:
arr = np.arange(12).reshape(3, 4)

print("3,4 Array \n ",arr)
newarr = arr.reshape(4, 3)

print("\n\n",newarr)

3,4 Array 
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**[Slide No. 20]**

10. Create two numpy array and concanate them .

In [21]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


**[Slide No.22]**

11. Create numpy array and search a number in it .

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 2)

print(x)

(array([1], dtype=int64),)


**[Slide No.26]**

12. Write a program to print 3,4 numpy array by any random number using random.randint function

In [27]:
array12=np.random.randint(10,90, (3,4))
print(array12)

[[40 43 78 88]
 [66 15 70 75]
 [19 82 71 64]]


**[Slide No. 30]**

13. Write a program to add two numpy array.

In [28]:
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
print ("1st array : ", arr1)  
print ("2nd array : ", arr2)  
   
out_arr = np.add(arr1, arr2)  
print ("added array : ", out_arr)

1st array :  [3 2 1]
2nd array :  [1 2 3]
added array :  [4 4 4]


14. Delete the second column from a given array and insert the following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])

In [36]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray=np.delete(sampleArray, 1, 1)
print(sampleArray)
newColumn = np.array([[10,10,10]])
 

print("Array after inserting column 2 on axis 1")
newColumn1 = numpy.insert(sampleArray , 1, newColumn, axis = 1) 
print (newColumn1)

[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]
